# Generated by Django 5.1.2 on 2024-10-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_rename_brand_ropa_marca_rename_size_ropa_talle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ropa',
            name='talle',
        ),
        migrations.AddField(
            model_name='ropa',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ropa',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
