# Generated by Django 5.1.2 on 2024-10-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_remove_ropa_talle_ropa_descripcion_ropa_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='fecha',
            field=models.DateField(),
        ),
    ]
